### ISSUE TITLE
Please Add a License

### ISSUE THREAD

**Issue by charJe** [lem-project/lem-mailbox#2]
I know this project is meant to be use as part of Lem, but it is a separate project. Just to clear things up, please add a license file and a `:license` field in the system definition. 

If I understand correctly, the absence of a license implies **all rights reserved** which is not desirable for open source and free software. As the author copyright holder (@Sasanidas), you can choose to do what you want with it, including using it in Lem. Since Lem has multiple authors though, things could become legally ambiguous.

I suggest using a copyleft license like the GPL 3 or AGPL 3 as these licenses provide the most freedoms to the end user and keep your software free. This would require Lem to also switch to a compatible copyleft license in a future version, so I understand if you do not want to go this route.

**Comment by Sasanidas** [comment]
Thanks for pointing out the license problem, I changed to license to MIT mostly because of the compatibility with the Lem project.

I'm a supported of Copyleft licenses, but I'm not the one who deiced the license for the Lem project so compatibility it's more important for this project :+1:
